---

- name: systemd daemon reload
  systemd:
    daemon_reload: true
  when: ansible_os_family | lower == "redhat" and ansible_distribution_major_version >= '7' or
        ansible_os_family | lower == "debian" and ansible_distribution_major_version >= '8'

- name: logstash restart
  service:
    name: logstash
    state: restarted

- name: logstash status
  wait_for:
    host: 127.0.0.1
    port: "{{ logstash.inputs.beats.port }}"
    delay: 60

- name: logstash hold version
  dpkg_selections:
    name: logstash
    selection: hold
  when: logstash.pin_version

- name: logstash lock version
  command: yum versionlock add logstash-{{ logstash.version }}
  args:
    warn: false
  when: logstash.pin_version
