---

- name: ensure dependencies are installed
  package:
    name:
      - yum-utils
      - yum-plugin-versionlock
      - libselinux-python
      - policycoreutils-python
      - java-1.8.0-openjdk.x86_64

- name: ensure Elastic repository is present
  yum_repository:
    name: "elastic-{{ logstash.version.split('.')[:1] | join('.') }}.x"
    description: "Elastic repository for version {{ logstash.version.split('.')[:1] | join('.') }}.x"
    file: "elastic-{{ logstash.version.split('.')[:1] | join('.') }}.x"
    baseurl: "https://artifacts.elastic.co/packages/{{ logstash.version.split('.')[:1] | join('.') }}.x/yum"
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: true
    enabled: true
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
